framework:
    messenger:
        transports:
          async_users:
            dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
          external_messages:
            dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
            options:
              auto_setup: true
              exchange:
                name: messages
                type: direct
                default_publish_routing_key: from_external
              queues:
                messages:
                  binding_keys: [ from_external ]

        routing:
          'App\Message\UserInfo': async_users
