framework:
    messenger:
        transports:
          async_users:
            dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
            serializer: App\Infrastructure\Messenger\ExternalJsonMessageSerializer
            options:
              auto_setup: true
              exchange:
                name: messages
                type: direct
                default_publish_routing_key: from_external
              queues:
                messages:
                  binding_keys: [ from_external ]

        routing:
          'App\Application\Query\GetUserData': async_users
